# KAFKA CONFIGURATION
BOOTSTRAP_SERVER=localhost:9092
CONSUMER_TOPIC=postgres_data
CONSUMER_GROUP=json_consumer
LIVE_TOPIC=gps_live_events
HISTORY_TOPIC=gps_history_events
SYNC_TOPIC=sync_action_topic
SYNC_CONSUMER_GROUP=sync_data

# REDIS CONFIGURATION
REDIS_SENTINAL_PORT=26379
REDIS_SENTINAL_HOST=localhost
REDIS_MASTER=mymaster

# MONGODB CONFIGURATION
MONGO_URI=mongodb://localhost:27017
MONGO_DB_NAME=fleet_management
MONGO_COLLECTION=device_metadata




